### ISSUE TITLE
Using on unsaved pens

### ISSUE THREAD

**Issue by virtual** [dizzyd/codopen#1]
Hi! Nice plugin. Just wanted to note that if you try to run it before saving or forking a pen, it will go visit Debug's profile (http://codepen.io/Debug/) so they might be getting a few more hits than usual :)

**Comment by dizzyd** [comment]
Thanks for the report! Fixed in 1.0.1 [https://github.com/dizzyd/codopen/commit/cecadc9afb9192e5d7167e2f8988ecc93d200fdb]

(N.B. - Chrome Web Store may take 60 mins to publish :( )
